### ISSUE TITLE
Add AED currency to Blink

### ISSUE THREAD

**Issue by agbegin** [GaloyMoney/blink#4321]
User has requested to add AED currency to Blink 
https://en.wikipedia.org/wiki/United_Arab_Emirates_dirham 

Represented with symbol AED in place of dollar sign
<img width="513" alt="Screenshot 2024-04-19 at 8 49 15 PM" src="https://github.com/GaloyMoney/galoy/assets/90297599/7517ddae-4b35-49f7-ab52-f03d7fd3f159">

**Comment by dolcalmi** [comment]
I have this symbol `د.إ` can you confirm?

**Comment by agbegin** [comment]
"That's Arabic. In English it's "AED"

Sounds like best is to stick with english letters for symbol

**Comment by dolcalmi** [comment]
added 3 months ago
