### ISSUE TITLE
Show some simple graph on dashboard

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/blink#4324]
Currently the dashboard only show current balance

It would be useful (asked my some users) to show an history of the balance over the days/weeks/months

Maybe with a usd and btc and total graph 

I think for now everything could be calculated on the browser. This might work for most client

Of course if the user were to have more than 100k or so tx, maybe this would not work, but for now this approach would work for most users

**Comment by nicolasburtey** [comment]
> Should we stick to the one-month (max) graph due to too much calculation, as we don't have balance at time of transaction?

I think we should show balance over time, and calculate it dynamically.
we should start by doing some unit testing here to test the behavior

I think it's better to get granular option from the user. I don't think month only is good. I think someone should be able to choose the day they want. 

> Also, for the total amount graph, we might need to convert the balance to a common currency, so calculation will be required there as well + also BTC movement calculation?

I'm not too sure. I would suggest starting with dollar, and when we have something we like we can iterate on having more currencies

**Comment by siddhart1o1** [comment]
>I think it's better to get granular option from the user. I don't think month only is good. I think someone should be able to choose the day they want.or

Yes, but the maximum duration should be one month or maybe six months. One year might involve too much calculation at runtime.

**Comment by nicolasburtey** [comment]
> Yes, but the maximum duration should be one month or maybe six months ? One year might involve too much calculation at runtime.

this has less to do with how many months, but more how many transactions there is. I think we should not have a limit here to get started, but rather see how this behave and then adjust as needed.

> If we want a total amount graph, then we will need data points equal to what we get from the btcPriceList query to match the timestamp and get the dollar price.

good point. maybe to get started, we can show the balance of the bitcoin wallet in bitcoin, and the stablesats balance in dollar, and see how this feels, and then can iterate from it.
