### ISSUE TITLE
Add Zambian Kwacha (ZMW) currency in Blink

### ISSUE THREAD

**Issue by agbegin** [GaloyMoney/blink#4510]
Requesting addition of Zambian Kwacha currency to Blink

The currency symbol to use in app is K, such as K50.  They use similar commas and periods to the dollar, so this would be how to show a larger value: K10,000.50

Details/symbols: https://en.wikipedia.org/wiki/Zambian_kwacha

It does not appear that Zambia has a "Blue rate" separate from the official exchange rates.

**Comment by dolcalmi** [comment]
added 3 weeks ago
